version: '4'
name: pgsql

services:
  pgsql:
    image: postgres:16.2
    ports:
    - 5432:5432
    volumes:
      - /var/db/postgres/data:/var/lib/postgres/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_credentials
    secrets:
      - db_credentials
secrets:
  db_credentials:
    file: ./pgsql_credentials
