/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.spring_demo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasName() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getClassName());
    }
}
